export const NAV_TOGGLE = Symbol('NAV_TOGGLE');
export const NAV_REMOVE = Symbol('NAV_REMOVE');
export const NAV_ADD = Symbol('NAV_ADD');

export const FOOTER_REMOVE = Symbol('FOOTER_REMOVE');
export const FOOTER_ADD = Symbol('FOOTER_ADD');

export const SERVICE_FETCH_START = Symbol('SERVICE_FETCH_START');
export const SERVICE_FETCH_SUCCESS = Symbol('SERVICE_FETCH_SUCCESS');
export const SERVICE_FETCH_FAILURE = Symbol('SERVICE_FETCH_FAILURE');

export const CATEGORIES_FETCH_START = Symbol('CATEGORIES_FETCH_START');
export const CATEGORIES_FETCH_SUCCESS = Symbol('CATEGORIES_FETCH_SUCCESS');
export const CATEGORIES_FETCH_FAILURE = Symbol('CATEGORIES_FETCH_FAILURE');

export const CATEGORIES_CREATE_START = Symbol('CATEGORIES_CREATE_START');
export const CATEGORIES_CREATE_SUCCESS = Symbol('CATEGORIES_CREATE_SUCCESS');
export const CATEGORIES_CREATE_FAILURE = Symbol('CATEGORIES_CREATE_FAILURE');

export const SET_PROJECT_MAIN_SUCCESS = Symbol('SET_PROJECT_MAIN_SUCCESS');
export const ADD_PHOTOS_SUCCESS = Symbol('ADD_PHOTOS_SUCCESS');
export const DELETE_PHOTO_SUCCESS = Symbol('DELETE_PHOTO_SUCCESS');

export const PROJECT_PICTURES_START = Symbol('PROJECT_PICTURES_START');
export const PROJECT_PICTURES_FAILURE = Symbol('PROJECT_PICTURES_FAILURE');
export const PROJECT_PICTURES_SUCCESS = Symbol('PROJECT_PICTURES_SUCCESS');

export const PROJECT_FETCH_START = Symbol('PROJECT_FETCH_START');
export const PROJECT_FETCH_SUCCESS = Symbol('PROJECT_FETCH_SUCCESS');
export const PROJECT_FETCH_FAILURE = Symbol('PROJECT_FETCH_FAILURE');

export const ADD_PROJECT_START = Symbol('ADD_PROJECT_START');
export const ADD_PROJECT_SUCCESS = Symbol('ADD_PROJECT_SUCCESS');
export const ADD_PROJECT_FAILURE = Symbol('ADD_PROJECT_FAILURE');

export const JOINUS_ADD_FILE = Symbol('JOINUS_ADD_FILE');
export const JOINUS_REMOVE_FILE = Symbol('JOINUS_REMOVE_FILE');
export const JOINUS_START = Symbol('JOINUS_START');
export const JOINUS_FAIL = Symbol('JOINUS_FAIL');
export const JOINUS_SUCCESS = Symbol('JOINUS_SUCCESS');

export const ADDNEWS_START = Symbol('ADDNEWS_START');
export const ADDNEWS_FAIL = Symbol('ADDNEWS_FAIL');
export const ADDNEWS_SUCCESS = Symbol('ADDNEWS_SUCCESS');

export const EDITNEWS_START = Symbol('EDITNEWS_START');
export const EDITNEWS_FAIL = Symbol('EDITNEWS_FAIL');

export const CONTACTUS_START = Symbol('CONTACTUS_START');
export const CONTACTUS_FAIL = Symbol('CONTACTUS_FAIL');
export const CONTACTUS_SUCCESS = Symbol('CONTACTUS_SUCCESS');

export const LOGIN_START = Symbol('LOGIN_START');
export const LOGIN_FAIL = Symbol('LOGIN_FAIL');
export const LOGIN_SUCCESS = Symbol('LOGIN_SUCCESS');

export const NEWSLIST_START = Symbol('NEWSLIST_START');
export const NEWSLIST_FAIL = Symbol('NEWSLIST_FAIL');
export const NEWSLIST_SUCCESS = Symbol('NEWSLIST_SUCCESS');

export const FILTER_PROJECTS = Symbol('FILTER_PROJECTS');
export const PROJECTSLIST_START = Symbol('PROJECTSLIST_START');
export const PROJECTSLIST_FAIL = Symbol('PROJECTSLIST_FAIL');
export const PROJECTSLIST_SUCCESS = Symbol('PROJECTSLIST_SUCCESS');

export const APLICANTS_START = Symbol('APLICANTS_START');
export const APLICANTS_FAIL = Symbol('APLICANTS_FAIL');
export const APLICANTS_SUCCESS = Symbol('APLICANTS_SUCCESS');

export const SINGLE_NEWS_START = Symbol('SINGLE_NEWS_START');
export const SINGLE_NEWS_FAIL = Symbol('SINGLE_NEWS_FAIL');
export const SINGLE_NEWS_SUCCESS = Symbol('SINGLE_NEWS_SUCCESS');

export const LANG_CHANGE = Symbol('LANG_CHANGE');

export const DELETE_APPLICANT_START = Symbol('DELETE_APPLICANT_START');
export const DELETE_APPLICANT_FAILURE = Symbol('DELETE_APPLICANT_FAILURE');
export const DELETE_APPLICANT_SUCCESS = Symbol('DELETE_APPLICANT_SUCCESS');

export const DELETE_NEWS_START = Symbol('DELETE_NEWS_START');
export const DELETE_NEWS_FAILURE = Symbol('DELETE_NEWS_FAILURE');
export const DELETE_NEWS_SUCCESS = Symbol('DELETE_NEWS_SUCCESS');

export const DELTET_PROJECT_START = Symbol('DELTET_PROJECT_START');
export const DELTET_PROJECT_FAIL = Symbol('DELTET_PROJECT_FAIL');
export const DELTET_PROJECT_SUCCESS = Symbol('DELTET_PROJECT_SUCCESS');

export const EDIT_PROJECT_START = Symbol('EDIT_PROJECT_START');
export const EDIT_PROJECT_FAIL = Symbol('EDIT_PROJECT_FAIL');
export const EDIT_PROJECT_SUCCESS = Symbol('EDIT_PROJECT_SUCCESS');

export const PROJECT_DETAILS_START = Symbol('PROJECT_DETAILS_START');
export const PROJECT_DETAILS_SUCCESS = Symbol('PROJECT_DETAILS_SUCCESS');
export const PROJECT_DETAILS_FAILURE = Symbol('PROJECT_DETAILS_FAILURE');

export const LATEST_PROJECT_START = Symbol('LATEST_PROJECT_START');
export const LATEST_PROJECT_SUCCESS = Symbol('LATEST_PROJECT_SUCCESS');
export const LATEST_PROJECT_FAILURE = Symbol('LATEST_PROJECT_FAILURE');

export const LATEST_NEWS_START = Symbol('LATEST_NEWS_START');
export const LATEST_NEWS_SUCCESS = Symbol('LATEST_NEWS_SUCCESS');
export const LATEST_NEWS_FAILURE = Symbol('LATEST_NEWS_FAILURE');

export const RESET_MESSAGE = Symbol('RESET_MESSAGE');

export const CONTACT_RESET_MESSAGE = Symbol('CONTACT_RESET_MESSAGE');

export const ADDSERVICE_START = Symbol('ADDSERVICE_START');
export const ADDSERVICE_SUCCESS = Symbol('ADDSERVICE_SUCCESS');
export const ADDSERVICE_FAIL = Symbol('ADDSERVICE_FAIL');

export const DELETE_SERVICE_START = Symbol('DELETE_SERVICE_START');
export const DELETE_SERVICE_SUCCESS = Symbol('DELETE_SERVICE_SUCCESS');
export const DELETE_SERVICE_FAILURE = Symbol('DELETE_SERVICE_FAILURE');

export const SINGLE_SERVICE_START = Symbol('SINGLE_SERVICE_START');
export const SINGLE_SERVICE_SUCCESS = Symbol('SINGLE_SERVICE_SUCCESS');
export const SINGLE_SERVICE_FAILURE = Symbol('SINGLE_SERVICE_FAILURE');

export const EDITSERVICE_START = Symbol('EDITSERVICE_START');
export const EDITSERVICE_SUCCESS = Symbol('EDITSERVICE_SUCCESS');
export const EDITSERVICE_FAIL = Symbol('EDITSERVICE_FAIL');

export const FETCH_TEAM_START = Symbol('FETCH_TEAM_START');
export const FETCH_TEAM_SUCCESS = Symbol('FETCH_TEAM_SUCCESS');
export const FETCH_TEAM_FAILURE = Symbol('FETCH_TEAM_FAILURE');

export const ADDMEMBER_START = Symbol('ADDMEMBER_START');
export const ADDMEMBER_SUCCESS = Symbol('ADDMEMBER_SUCCESS');
export const ADDMEMBER_FAIL = Symbol('ADDMEMBER_FAIL');

export const DELETE_MEMBER_SUCCESS = Symbol('DELETE_MEMBER_SUCCESS');

export const FETCH_MEMBER_START = Symbol('FETCH_MEMBER_START');
export const FETCH_MEMBER_SUCESS = Symbol('FETCH_MEMBER_SUCESS');
export const FETCH_MEMBER_FAIL = Symbol('FETCH_MEMBER_FAIL');

export const EDITMEMBER_START = Symbol('EDITMEMBER_START');
export const EDITMEMBER_SUCCESS = Symbol('EDITMEMBER_SUCCESS');
